apiVersion: apps/v1
kind: Deployment
metadata:
  name: apiserver
  namespace: default
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  selector:
    matchLabels:
      app: apiserver
  template:
    metadata:
      labels:
        app: apiserver
    spec:
      automountServiceAccountToken: true
      containers:
        - args:
            - -dbConnection=postgresql://postgres:1234@10.20.0.95:5432/db-geocube
            - -local
            - -psEventsTopic=events
            - -psConsolidationsTopic=consolidations
            - -ingestionStorage=/geocube-datasets
            - -maxConnectionAge=3600
            - -workers=1
            - -cancelledJobs=/geocube-cancelled-jobs
          env:
            - name: PUBSUB_EMULATOR_HOST
              value: 0.0.0.0:8085
          image: geocube-server:latest
          imagePullPolicy: IfNotPresent
          name: apiserver
          ports:
            - containerPort: 8080
              protocol: TCP
          volumeMounts:
          - mountPath: /tmp
            name: local-storage
          resources: {}
      terminationGracePeriodSeconds: 120
      volumes:
        - name: local-storage
          emptyDir: {}
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
