apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: autoscaler-role
rules:
  - apiGroups: ['']
    verbs: ['get', 'list','delete','create']
    resources:
      - pods
    resources:
      - replicationcontrollers
